name=input("Enter your name")
age=input("Enter your age")
birthyear=int(birthyear)+int(age)
hundredyear=int(birthyear)+int(100)
num=int(hundredyear)
print(f"Hey{name}!You will turn 100 years old in{num}")
